development:
  RAILS_SECRET_KEY_BASE: 2eddb9a3aada334619b89021d8c935aeef9f5fa29caf84cc56a63d38c085eb65995621c6d83b4c4c40d57b86f8dab8ec3addbd2811e1ccd5e5007ad5d5dd334d
  #RAILS_ENV: development
  PUMA_MIN_THREADS: 2
  PUMA_MAX_THREADS: 5
  WEB_CONCURRENCY: 0

  DATABASE_HOST: postgres
  DATABASE_NAME: shizoid
  DATABASE_PASSWORD: 10241
  DATABASE_PORT: 5432
  DATABASE_USERNAME: emil
  DB_POOL_SIZE: 40

  SIDEKIQ_CONCURRENCY: 25
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_SIDEKIQ_DB: 1
  REDIS_CONTEXT_DB: 2
  #REDIS_PASSWORD
  CONTEXT_SIZE: 50

  WEBHOOK_URL: "https://localhost"
  TELEGRAM_TOKEN: "5574390282:AAFwZtnLtqqoXADIUJ7JRvGq-AhoNGpPoqs"
  BOT_OWNERS: 11111,222222
  #ALLOW_TO_ALL: true
  #SENTRY_DSN:

  STOPCOVID_URL: "https://xn--80aesfpebagmfblc0a.xn--p1ai"
  CAS_URL: "https://api.cas.chat"
